In [19]:
%reset

In [4]:
import tensorflow as tf
import tensorflow_hub as hub
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import re
import umap # dimensionality reduction
from sklearn.cluster import DBSCAN
# from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import hdbscan
from deep_translator import GoogleTranslator

# Preparing Dataset

In [5]:
dataset=pd.read_csv("C:/Users/rbw19/Downloads/dataset.csv",on_bad_lines='skip')
ref=dataset
dataset=dataset[["title",'category_id','contents',"agency_id",'tweet_text']]
dataset.head(5)

title  category_id  \
0  سمو ولي العهد يغادر مصر بعد المشاركة في مؤتمري...  أخبار محلية   
1  \r\n                                    "التأم...  أخبار محلية   
2                            بسم اللّه الرحمن الرحيم  أخبار محلية   
3            مجلس الوزراء يعتمد مراسيم تعيين قياديين  أخبار محلية   
4  البيدان لـ «الوطن»: المنشآت وتطوير القوانين وم...  أخبار محلية   

                                            contents  \
0  \n                                    بحفظ الل...   
1                                \n\n\n\n\n\n \n\n\n   
2                                                      
3  \n                                    (كونا) -...   
4  \n                                    اعرب مدي...   

                             agency_id  tweet_text  
0                                الوطن         NaN  
1  المؤسسة العامة للتأمينات الاجتماعية         NaN  
2           جهاز متابعة الأداء الحكومي         NaN  
3                                الوطن         NaN  
4                                الوطن         NaN

In [19]:
dataset.shape

(1421, 5)

In [6]:
dataset.fillna("",inplace=True)

C:\Users\rbw19\AppData\Local\Temp\ipykernel_14112\793188746.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.fillna("",inplace=True)


In [7]:
exp='[\u0627-\u064aA-Za-z]+' #re to get arabic and english , i had eliminated numbers and special characters because they dont have much influence 
dataset["title"]=dataset["title"].apply(lambda data : " ".join(re.findall(exp,data)))
dataset['category_id']=dataset["category_id"].apply(lambda data: " ".join(re.findall(exp,data)) )
dataset["contents"]=dataset['contents'].apply(lambda data : " ".join(re.findall(exp,data)))
dataset["agency_id"]=dataset["agency_id"].apply(lambda data : " ".join(re.findall(exp,data)))
dataset["tweet_text"]=dataset["tweet_text"].apply(lambda data: " ".join(re.findall(exp,data)))


C:\Users\rbw19\AppData\Local\Temp\ipykernel_14112\776271922.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["title"]=dataset["title"].apply(lambda data : " ".join(re.findall(exp,data)))
C:\Users\rbw19\AppData\Local\Temp\ipykernel_14112\776271922.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['category_id']=dataset["category_id"].apply(lambda data: " ".join(re.findall(exp,data)) )
C:\Users\rbw19\AppData\Local\Temp\ipykernel_14112\776271922.py:4: SettingWithCopyWarning: 
A value is tr

In [8]:
def cleanText(text):
    text = BeautifulSoup(text, "lxml").text
    text = re.sub(r'\|\|\|', r' ', text) 
    text = re.sub(r'http\S+', r'<URL>', text)
    # text = text.lower()
    # text = text.replace('x', '')
    return text

dataset["title"]=dataset["title"].apply(lambda data:cleanText(data))
dataset["contents"]=dataset["contents"].apply(lambda data:cleanText(data))
dataset["category_id"]=dataset["category_id"].apply(lambda data:cleanText(data))
dataset["agency_id"]=dataset["agency_id"].apply(lambda data:cleanText(data))
dataset["tweet_text"]=dataset["tweet_text"].apply(lambda data:cleanText(data))

C:\Users\rbw19\AppData\Local\Temp\ipykernel_14112\3001530856.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["title"]=dataset["title"].apply(lambda data:cleanText(data))
C:\Users\rbw19\AppData\Local\Temp\ipykernel_14112\3001530856.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["contents"]=dataset["contents"].apply(lambda data:cleanText(data))
C:\Users\rbw19\AppData\Local\Temp\ipykernel_14112\3001530856.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice

In [9]:
dataset

title  category_id  \
0     سمو ولي العهد يغادر مصر بعد المشاركة في م تمري...   خبار محلية   
1     الت مينات تشارك في الاجتماع الحادي والعشرين لر...   خبار محلية   
2                               بسم الل ه الرحمن الرحيم   خبار محلية   
3                مجلس الوزرا يعتمد مراسيم تعيين قياديين   خبار محلية   
4     البيدان لـ الوطن المنش ت وتطوير القوانين ومعال...   خبار محلية   
...                                                 ...          ...   
1416  التقدم العلمي تعزز التعاون ال كاديمي والبحثي ب...  خبار العلوم   
1417               استكشاف الفضا ل لهام ال جيال القادمة  خبار العلوم   
1418  م سسة الكويت للتقدم العلمي في معرض الشارقة الد...  خبار العلوم   
1419  م سسة التقدم العلمي تعلن سما الفا زين بجوا زها...  خبار العلوم   
1420  الدكتورة ليلى حبيب برعت في بحثها فحصدت جا زة ا...  خبار العلوم   

                                               contents  \
0     بحفظ الله ورعايته غادر ممثل حضرة صاحب السمو مي...   
1                                                         
2                                                         
3     كونا علن نا ب ر يس مجلس الوزرا ووزير الدولة لش...   
4     اعرب مدير عام هي ة الشباب والرياضة يوسف البيدا...   
...                                                 ...   
1416  زار دولة الكويت وفد من جامعة كاليفورنيا بيركلي...   
1417  خاطب الحضور من الناش ة والشباب الذين مل وا قاع...   
1418  تشارك م سسة الكويت للتقدم العلمي في معرض الشار...   
1419  علنت م سسة الكويت للتقدم العلمي اليوم سما الفا...   
1420  شيوعه في الوطن العربي والكويت تحديد ا حثني على...   

                                agency_id tweet_text  
0                                   الوطن             
1     الم سسة العامة للت مينات الاجتماعية             
2               جهاز متابعة ال دا الحكومي             
3                                   الوطن             
4                                   الوطن             
...                                   ...        ...  
1416           م سسة الكويت للتقدم العلمي             
1417           م سسة الكويت للتقدم العلمي             
1418           م سسة الكويت للتقدم العلمي             
1419           م سسة الكويت للتقدم العلمي             
1420           م سسة الكويت للتقدم العلمي             

[1421 rows x 5 columns]

In [10]:
data=dataset["title"]+dataset["contents"]+dataset["category_id"]+dataset["agency_id"]+dataset["tweet_text"]
data=data.to_list()

In [11]:
len(data)

1421

# Vectorizing

In [12]:
module_url = "https://tfhub.dev/google/universal-sentence-encoder/4" # this is already a pretrained model ,so need of saving this model with our data
model = hub.load(module_url)

In [13]:
embedding_gen = model(data)  #

In [14]:
embedding_gen.shape

TensorShape([1421, 512])

# Dimensionality Reduction

In [15]:
umap_embeddings = (umap.UMAP(n_neighbors=10, n_components=20, metric='cosine', 
                                random_state=24).fit_transform(embedding_gen))

In [38]:
print(type(umap_embeddings),'\n',umap_embeddings.shape,'\n',umap_embeddings)
print()

<class 'numpy.ndarray'> 
 (1421, 20) 
 [[10.390603   5.775942   3.3013356 ...  7.584819   7.4700317  6.118715 ]
 [10.9187     4.925012   3.203601  ...  7.6478996  6.8168926  4.6543584]
 [11.351933   4.14504    4.2030516 ...  7.614952   6.926056   4.985949 ]
 ...
 [10.376332   5.4243307  2.6391237 ...  7.6943326  6.542361   4.3580656]
 [10.747433   5.014059   2.963721  ...  7.6186256  6.471488   4.4896865]
 [10.740151   4.914826   2.954909  ...  7.9106426  6.637452   4.191994 ]]



# HDBScan

In [16]:
clusters = hdbscan.HDBSCAN(min_cluster_size = 3,
                               metric='euclidean', 
                                ).fit(umap_embeddings)
# hdbscan.HDBSCAN(algorithm='best', alpha=1.0, approx_min_span_tree=True,
#                 gen_min_span_tree=False, leaf_size=40,metric='euclidean',
#                 min_cluster_size=5, min_samples=None, p=None)
print(clusters.labels_,len(clusters.labels_))
print(np.unique(clusters.labels_),'\n',len(np.unique(clusters.labels_)))

[ 2 -1 49 ... 22 21 -1] 1421
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46
 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70
 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94
 95 96 97 98] 
 100


# Saving the model

In [17]:
import pickle

In [18]:
pickle.dump(clusters,open('cat_100.sav','wb'))

# load the model 

In [3]:
model=pickle.load(open("cat_100.sav",'rb'))
print(model.labels_,len(model.labels_))
# print(np.unique(clusters.labels_),'\n',len(np.unique(clusters.labels_)))

c:\anaconda\envs\machine_learning\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\anaconda\envs\machine_learning\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
c:\anaconda\envs\machine_learning\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


[ 2 -1 49 ... 22 21 -1] 1421


# Model evaluation

In [44]:
cluster=[]
for idx in range(len(clusters.labels_)):
    if clusters.labels_[idx]==30: #taking dataponits of 10th cluster
        cluster.append(idx)

In [45]:
news_cluster=[]
for dp in cluster:
    news_cluster.append(GoogleTranslator(source='auto', target='en').translate(data[dp][:200])) #limiting to 200 --> for easy translation
news_cluster

['The agency discusses the latest developments of the railway network project His Excellency Sheikh Hamad Mishaal Al Hamad Al-Sabah, the head of the government’s follow-up agency, held a meeting with specialists in the General Authority for Roads and Land Transport to follow up on the latest developments of the network project',
 'Sheikh Hamad Al-Mishal, the head of the apparatus, presents recommendations to the Cabinet of Ministers to raise the level of the government',
 'The Legislative Council is discussing lifting the immunity of MP Muhannad Al-Sayer and a set of proposals for laws.',
 'Two people were injured in a six-way quarrel in Al-Jahra Hospital. Two people were moderately injured as a result of a quarrel that took place at dawn today between six people in front of Al-Jahra Hospital, and I was moved inside. A source said that two quarrels are being caught who escaped with a vehicle. A number was captured.',
 'Two expatriates came to Al-Baad for roaming with two air rifles. Th

In [60]:
# news_cluster=[]
ids=[]
for dp in cluster:
    # news_cluster.append(data[dp]) #limiting to 200 --> for easy translation
    # print(data.index(data[dp]))
    ids.append(data.index(data[dp]))
ids 

[17,
 65,
 190,
 254,
 283,
 298,
 378,
 391,
 514,
 538,
 596,
 730,
 850,
 862,
 890,
 1015,
 1104,
 1113,
 1123]

In [64]:
ref

[['post_id', 'title', 'category_id', 'contents', 'agency_id', 'tweet_text']]

In [117]:
cluster_30=pd.DataFrame(ref.iloc[ids])

In [118]:
def translator(data):
    return GoogleTranslator(source='auto', target='en').translate(data)

cluster_30["category_id"]=cluster_30["category_id"].apply(lambda data : translator(data))

In [120]:
cluster_30.to_csv("cluster_30.csv")

In [77]:
ref.iloc[ids]["category_id"].to_list()

for dp in ref.iloc[ids]["category_id"].to_list():
    print(GoogleTranslator(source='auto', target='en').translate(dp))

local news
local news
National Assembly News
Legal and security news
Legal and security news
Legal and security news
Economic news
Economic news
Art and culture news
Art and culture news
Art and culture news
News, meetings, programs and reports
Local and international news
Local and international news
Local and international news
Education news
community and activities
community and activities
Technology News


In [112]:
pd.Dataframe(ref.iloc[ids][["post_id","post_url","agency_id","contents"]]

post_id                                           post_url  \
17         41  https://www.gpf.gov.kw/Ar/newsdetails.aspx?id=...   
65        206  https://www.gpf.gov.kw/Ar/newsdetails.aspx?id=...   
190       625                   https://istqlalnews.com/?p=14367   
254       649  https://www.cckwt.cc/%d8%a3%d9%85%d9%86/%d8%a5...   
283      1058                      https://www.alraqeeb.news/810   
298      1173              http://www.alhakea.com/word/?p=420614   
378       637                    https://q8times.com/284094.html   
391       725                     https://pressnewskw.com/28655/   
514       239                          http://fn1q8.com/?p=53370   
538       509                          http://fn1q8.com/?p=53681   
596      2270                       http://alshahedkw.com/339568   
730      7862                http://alhrernews.com/archives/4795   
850     13739  http://www.alwasat.com.kw/ArticleDetail.aspx?i...   
862     17607  https://www.kuna.net.kw/ArticleDetails.aspx?id...   
890     18733  https://www.kuna.net.kw/ArticleDetails.aspx?id...   
1015     2003  https://taleem.com.kw/2022/09/16/%d8%b7%d9%84%...   
1104     1676                       http://alshahedkw.com/194073   
1113     2041              https://alerada.net/2022/11/07/144550   
1123      416  https://www.cait.gov.kw/Home/News/اخبار-الكويت...   

                               agency_id  \
17            جهاز متابعة الأداء الحكومي   
65            جهاز متابعة الأداء الحكومي   
190          جريدة الإستقلال الإلكترونية   
254                         جرائم ومحاكم   
283                   ‏اخبار الرقيب نيوز   
298                        جريدة الحقيقة   
378                           كويت تايمز   
391                             برس نيوز   
514                                فن ون   
538                                فن ون   
596                               الشاهد   
730                          الحرير نيوز   
850                                الوسط   
862        كونا - وكالة الانباء الكويتية   
890        كونا - وكالة الانباء الكويتية   
1015             جريدة تعليم الالكترونية   
1104                              الشاهد   
1113                       صحيفة الإرادة   
1123  الجهاز المركزي لتكنلوجيا المعلومات   

                                               contents  
17     \r\n                            \n\n\r\n     ...  
65     \r\n                            \n\n\r\n     ...  
190   تعقد لجنتان برلمانيتان اجتماعين اليوم الإثنين ...  
254   أصيب شخصان بجروح متوسطة جراء مشاجرة وقعت فجر ا...  
283   وأكدت الإدارة العامة للعلاقات والإعلام الأمني ...  
298   قالت الإدارة العامة للعلاقات والإعلام الأمني ب...  
378   ارتفع سعر برميل النفط الكويتي 46ر2 دولار ليبلغ...  
391   انخفض سعر برميل النفط الكويتي 1.24 دولار ليبلغ...  
514   سعيدة جدًا بإختياري سفيرة لإكوال سبوتيفاي لشهر...  
538   كشف نقيب المهن التمثيلية في مصر الفنان د. أشرف...  
596   تم اليوم الأحد الموافق 22/5/2022 انعقاد الجمعي...  
730                                                 NaN  
850   عقد مجلس الوزراء اجتماعه الأسبوعي امس برئاسة ر...  
862                   الكويت - 8 - 11 (كونا) -- ارتف...  
890                   الكويت - 8 - 11 (كونا) -- استق...  
1015  جريدة تعليم\n\n\nأعلن الاتحاد الوطني لطلبة الك...  
1104  اعرب مدير عام شركة يونيفرسال رياض الغريب عن سع...  
1113  جاء ذلك في بيان صحفي اليوم الاثنين عقب اجتماع ...  
1123  صدر أمس مرسوم بتعيين نواب لمدير عام الجهاز الم...

## Cosine Similarity measeure to verify hdbscan

In [102]:
len(cluster)

19

In [103]:
cluster_30_embed=[]
for point in cluster:
    # print("\n umap_embedding",umap_embeddings[point],"index",data.index(data[point]))
    cluster_30_embed.append(umap_embeddings[point])
# cluster_30_embed
umap_embed_30=pd.DataFrame(cluster_30_embed)

In [105]:
from sklearn.metrics.pairwise import cosine_similarity,cosine_distances

In [106]:
similarity_table=cosine_similarity(umap_embed_30)

In [109]:
pd.DataFrame(similarity_table)

0         1         2         3         4         5         6   \
0   1.000000  0.999622  0.999954  0.999963  0.999774  0.999925  0.999911   
1   0.999622  1.000000  0.999430  0.999611  0.999869  0.999755  0.999716   
2   0.999954  0.999430  1.000000  0.999866  0.999607  0.999851  0.999845   
3   0.999963  0.999611  0.999866  1.000000  0.999829  0.999926  0.999885   
4   0.999774  0.999869  0.999607  0.999829  1.000000  0.999936  0.999731   
5   0.999925  0.999755  0.999851  0.999926  0.999936  1.000000  0.999832   
6   0.999911  0.999716  0.999845  0.999885  0.999731  0.999832  1.000000   
7   0.999877  0.999663  0.999751  0.999906  0.999714  0.999780  0.999966   
8   0.999789  0.999862  0.999654  0.999839  0.999912  0.999879  0.999889   
9   0.999816  0.999789  0.999795  0.999769  0.999808  0.999879  0.999894   
10  0.999787  0.999953  0.999625  0.999769  0.999854  0.999818  0.999879   
11  0.999687  0.999932  0.999555  0.999700  0.999934  0.999861  0.999752   
12  0.999714  0.999991  0.999533  0.999712  0.999916  0.999829  0.999776   
13  0.999906  0.999756  0.999819  0.999908  0.999797  0.999866  0.999992   
14  0.999756  0.999877  0.999577  0.999833  0.999938  0.999865  0.999842   
15  0.999843  0.999910  0.999763  0.999800  0.999889  0.999911  0.999893   
16  0.999684  0.999928  0.999603  0.999617  0.999817  0.999799  0.999781   
17  0.999762  0.999725  0.999786  0.999668  0.999738  0.999841  0.999794   
18  0.999816  0.999950  0.999705  0.999777  0.999892  0.999884  0.999878   

          7         8         9         10        11        12        13  \
0   0.999877  0.999789  0.999816  0.999787  0.999687  0.999714  0.999906   
1   0.999663  0.999862  0.999789  0.999953  0.999932  0.999991  0.999756   
2   0.999751  0.999654  0.999795  0.999625  0.999555  0.999533  0.999819   
3   0.999906  0.999839  0.999769  0.999769  0.999700  0.999712  0.999908   
4   0.999714  0.999912  0.999808  0.999854  0.999934  0.999916  0.999797   
5   0.999780  0.999879  0.999879  0.999818  0.999861  0.999829  0.999866   
6   0.999966  0.999889  0.999894  0.999879  0.999752  0.999776  0.999992   
7   1.000000  0.999870  0.999775  0.999850  0.999675  0.999735  0.999971   
8   0.999870  1.000000  0.999914  0.999910  0.999932  0.999900  0.999936   
9   0.999775  0.999914  1.000000  0.999846  0.999899  0.999824  0.999907   
10  0.999850  0.999910  0.999846  1.000000  0.999884  0.999969  0.999897   
11  0.999675  0.999932  0.999899  0.999884  1.000000  0.999946  0.999806   
12  0.999735  0.999900  0.999824  0.999969  0.999946  1.000000  0.999816   
13  0.999971  0.999936  0.999907  0.999897  0.999806  0.999816  1.000000   
14  0.999852  0.999987  0.999846  0.999908  0.999925  0.999916  0.999900   
15  0.999800  0.999929  0.999965  0.999941  0.999948  0.999938  0.999910   
16  0.999650  0.999865  0.999930  0.999902  0.999945  0.999925  0.999800   
17  0.999622  0.999802  0.999970  0.999754  0.999856  0.999756  0.999798   
18  0.999801  0.999923  0.999929  0.999971  0.999946  0.999970  0.999896   

          14        15        16        17        18  
0   0.999756  0.999843  0.999684  0.999762  0.999816  
1   0.999877  0.999910  0.999928  0.999725  0.999950  
2   0.999577  0.999763  0.999603  0.999786  0.999705  
3   0.999833  0.999800  0.999617  0.999668  0.999777  
4   0.999938  0.999889  0.999817  0.999738  0.999892  
5   0.999865  0.999911  0.999799  0.999841  0.999884  
6   0.999842  0.999893  0.999781  0.999794  0.999878  
7   0.999852  0.999800  0.999650  0.999622  0.999801  
8   0.999987  0.999929  0.999865  0.999802  0.999923  
9   0.999846  0.999965  0.999930  0.999970  0.999929  
10  0.999908  0.999941  0.999902  0.999754  0.999971  
11  0.999925  0.999948  0.999945  0.999856  0.999946  
12  0.999916  0.999938  0.999925  0.999756  0.999970  
13  0.999900  0.999910  0.999800  0.999798  0.999896  
14  1.000000  0.999896  0.999824  0.999718  0.999904  
15  0.999896  1.000000  0.999969  0.999931  0.999992  
16  0.999824  0.999969  1.000000 

# server based approach

In [ ]:
#for everyday 
    # get the complete dataset
    # pass to the model
    # get its cluster label and store it
    # reranking recommmendations --> recommendations are ranked based on either popularity,freshness and etc  --> we cant do popularity beacuse we didn't published the website so far -- freshness can be considered
    # based on the recommendation select top n fresh news for each cluster --> say if we have 30 clusters then 10 news for each cluster is taken and store in db so that we can recommnend users based on that
