In [9]:
import pandas as pd
from sentence_transformers import SentenceTransformer, util

In [8]:
news = pd.read_csv("arabic_data.csv",on_bad_lines='skip')
news.columns=["title","contents","category","author_name"]
cont = []
cont.append(news.contents[10])
cont.append(news.contents[11])
cont.append(news.contents[12])
title = news.title[13]

In [25]:
# print(news.contents[10])
# print(news.contents[11])
# print(news.contents[12])
print(news.title[13])

«الأرصاد»: طقس اليوم.. حار


from the translation we can understand that cont sentences are related to politics and government <br>
but title varible has news related to weather

In [10]:
model = SentenceTransformer('distiluse-base-multilingual-cased-v1')

Downloading:   0%|          | 0.00/690 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/114 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.38k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/556 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/539M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/452 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/341 [00:00<?, ?B/s]

In [15]:
query_embedding = model.encode(title) #query for which the vector has to be calculated
passage_embedding = model.encode(cont) #we have 3 entries


# print("Similarity:", util.dot_score(query_embedding, passage_embedding))


512 3 <class 'numpy.ndarray'>


In [18]:
print(type(query_embedding),query_embedding.shape,passage_embedding.shape) #

<class 'numpy.ndarray'> (512,) (3, 512)


# Tensorflow method

In [32]:
### Universal Sentence Encoder
import tensorflow as tf
import tensorflow_hub as hub
from sklearn.metrics.pairwise import cosine_similarity

In [33]:


module_url = "https://tfhub.dev/google/universal-sentence-encoder/4" 
model = hub.load(module_url)

content = ['قال وزير ال وقاف والش ون ال سلامية الكويتي عيسى الكندري اليوم ال ربعا ن الكويت قيادة وحكومة وشعبا اهتمت بحفظ القر ن الكريم ودعم ومساندة حفظته وتشجيعهم وتكريمهم جا ذلك في كلمة الوزير الكندري لقاها نيابة عنه ال مين العام لل مانةالعامة لل وقاف بال نابة منصور الصقعبي خلال علان سما الفا زين والفا زات ال وا ل والجهات الفا زة بدروع مسابقة الكويت الكبرى لحفظ القر ن الكريم وتجويده ال التي قيمت برعاية سامية من لدن سمو مير البلاد الشيخ نواف ال حمد الجابر الصباح تحت شعار اطم ن و وضح ن مانة ال وقاف باعتبارها الجهة الرسمية التي سندت اليها اختصاصات الدعوة لى الوقف والقيام بكل ما يتعلق بش ونه بما في ذلك دارة مواله واستثمارها وصرف ريعها في حدود شروط الواقف وبما يحقق المقاصد الشرعية للوقف وتنمية المجتمع حضاريا وثقافيا واجتماعيا لتخفيف العب عن المحتاجين في المجتمع تقوم بجهد را د ومتميز في خدمة كتاب الله تعالى ولفت لى ن ال مانة تبذل كل الطاقات لخدمة القر ن الكريم ووضعه في المنزلة ال سمى لكل عمالها بهدف زيادة عدد حفاظه والمشاركين كما ونوعا لنيل شرف المنافسة في هذه المسابقة على مدار سنواتها المتعاقبة وذكر ن جمالي عدد المشاركين هذا العام بلغ متسابقا ومتسابقة ومن تم اختبارهم بلغ متسابقا ومتسابقة منهم من الذكور و من ال ناث وبلغ عمر كبر متسابقة عاما من شريحة الصم الشريحة الثانية وبين الكندري ن عدد الجهات المشاركة بلغ جهة خيرية ورسمية و جمالي عدد الفا زين في مختلف شرا ح وف ات المسابقة ذكورا و ناثا وعدد الفا زين من ف ات ذوي الاحتياجات الخاصة بلغ فا زا وفا زة وعدد الفا زين من الم سسات ال صلاحية وال حداث بلغ فا زا وفا زة وقال ن درع التفوق العام حصلت عليها جمعية بيادر السلام الخيرية والدرع الذهبية حصلت عليها وزارة ال وقاف والش ون ال سلامية والدرع الفضية حصلت عليها مبرة المتميزين لخدمة علوم القر ن والعلوم الشرعية والدرع البرونزية حصلت عليها كل من جمعية ال صلاح الاجتماعي ومبرة دشتي الخيرية وجمعية الماهر بالقر ن الكريم وعلومه',
 'صدر وزير التجارة والصناعة د عبدالله السلمان قرارا وزاريا بش ن عادة تشكيل المجلس الت ديبي بجهاز حماية المنافسة وبموجب القرار تمت عادة تشكيل المجلس بر اسة وكيل محكمة التمييز المستشار د عبيد العجمي والمستشار حمود محمد المطوع نا با للر يس وعضوية كل من المستشار محمد جاسم بهمن المستشار بمحكمة الاست ناف وحيدر طاهر الحرز ويوسف حسن قراشي ويتولى المجلس الفصل في المسا لة الت ديبية المحالة ليه من مجلس دارة الجهاز والمتعلقة بالمخالفات الواردة في المادة من حكام القانون في ش ن حماية المنافسة وينص قرار وزير التجارة والصناعة على ان تكون مدة عمل المجلس سنوات من تاريخ صدور القرار وتصرف للمجلس المكاف ة المالية الشهرية المقررة بالقرار الوزاري على ن يلغى كل حكم يتعارض مع حكام هذا القرار كما يلغى القرار الوزاري والقرار الوزاري وكل ما يعمل به من حكام',
 'تقدم وزير الداخلية وزير الدفاع بال نابة الشيخ ثامر العلي مشيعي جثامين شهيدا من شهدا الكويت الابرار في مقبرة الصليبيخات وسط حضور عدد غفير من المواطنين وقال العلي نقلت قبل قليل تحيات واعتزاز ومواساة صاحب السمو امير البلاد وسمو ولي عهده الامين الى ذوي الشهدا و ضاف الكويت اليوم احتضنت شهيدا وهذه كوكبة جديدة من الشهدا نس ل الله تعالى ان نصل الى ما وصلوا ليه شهدا حيا عند ربهم يرزقون ونبارك لذويهم وشارك في التشييع وزير التربية الدكتور علي المضف ووزير النفط وزير التعليم العالي الدكتور محمد الفارس والنا ب مساعد العارضي الذي قال يجب نقل قصص تضحيات الشهدا لل جيال القادمة كما شارك عدد من القيادات ال منية في وزارتي الداخلية والدفاع والحرس الوطني وقوة ال طفا']

embeddings = model(content)
similarity = cosine_similarity(embeddings)
print(similarity)

[[1.0000002  0.7312218  0.6654273 ]
 [0.7312218  0.9999999  0.86209613]
 [0.6654273  0.86209613 0.99999994]]


In [35]:
embeddings

<tf.Tensor: shape=(3, 512), dtype=float32, numpy=
array([[-0.0566675 , -0.01732942, -0.04934503, ...,  0.04665867,
        -0.0491011 , -0.05969096],
       [-0.04933674,  0.00606731, -0.05401601, ...,  0.01358067,
        -0.06695798, -0.07236457],
       [-0.05852233,  0.01354187, -0.05166337, ...,  0.04519889,
        -0.07243302, -0.07429723]], dtype=float32)>